In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np

In [3]:
array =np.array([1,2,3])
print(array)

[1 2 3]


In [4]:
array.shape

(3,)

In [5]:
array2= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
array2.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [6]:
array.dtype.name

'int64'

In [7]:
array2.size

15

In [8]:
type(array2)

numpy.ndarray

In [9]:
array3= np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
array3.shape

(3, 5)

In [11]:
zeros = np.zeros((3,4))

In [12]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.empty((4,5))

array([[0. , 0. , 0.3, 1. , 0. ],
       [0. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 0. , 0. ],
       [1. , 0.5, 0. , 0. , 1. ]])

In [14]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
a= np.linspace(0,10,20)
a

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
a= np.array([1,2,3])
b = np.array([5,5,3])
print(a+b)

[6 7 6]


In [17]:
a-b

array([-4, -3,  0])

In [18]:
a*b

array([ 5, 10,  9])

In [19]:
liste = {1,2,3,4}

array = np.array([5,6,7,8])
print(liste)
print(array)

{1, 2, 3, 4}
[5 6 7 8]


In [20]:
array = np.array(liste)
array

array({1, 2, 3, 4}, dtype=object)

In [21]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [22]:
b=a
c=a
b[0]=6
print(a,b,c)

[6 2 3] [6 2 3] [6 2 3]


In [23]:
d = a.copy()
d

array([6, 2, 3])

In [24]:
a[0]=6
d

array([6, 2, 3])

In [25]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
print(a[0])

1


In [27]:
print(a[0:4])

[1 2 3 4]


In [28]:
a[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [29]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
print(b[1,1])

7


In [31]:
print(b[:,1])

[2 7]


In [32]:
print(b[1,:])

[ 6  7  8  9 10]


In [33]:
print(b[1,1:4])

[7 8 9]


In [34]:
b[-1,:]

array([ 6,  7,  8,  9, 10])

In [35]:
b[:,-1]

array([ 5, 10])

In [36]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
b.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
b.resize(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])